### ISSUE TITLE
переход с createSignature на createAttachedSignature

### ISSUE THREAD

**Issue by code-by** [vgoma/crypto-pro#102]
сейчас на проекте использую `createSignature` (версия 2.3.0), метод отмечен устаревшим , нужно использовать `createAttachedSignature` или `createDetachedSignature`
при работе с `createSignature` в качестве второго параметра `messageHash` передаю base64 (сделанный из pdf-файла), третий параметр `detachedSignature` - `true`
при изменении на `createDetachedSignature` и использовании теже данных параметров `thumprint`, `messageHash` получаю "Ошибка при установке хеша"
что делаю не так? спасибо

**Comment by vgoma** [comment]
Работу описанных действий с вашим файлом можно проверить [в примере](https://github.com/vgoma/crypto-pro#example-script-tag) запустив его локально.
