### ISSUE TITLE
Получение серийного номера сертификата

### ISSUE THREAD

**Issue by mihalichpalich** [vgoma/crypto-pro#108]
Привет. Можно ли с помощью библиотеки получить серийный номер сертификата?

**Comment by Skayloo** [comment]
Вроде можно через getCadesProps("SerialNumber")

**Comment by vgoma** [comment]
@mihalichpalich привет.

> Вроде можно через getCadesProps("SerialNumber")

@Skayloo прав, спасибо за ответ.
