### ISSUE TITLE
метод getCertList не работает после минификации с помощью UglifyJs

### ISSUE THREAD

**Issue by t0lik** [vgoma/crypto-pro#11]
При вызове getCertList падает с ошибкой: t.Item is not a function. По факту Item при этом является промисом.

Окружение: 
Node: 8.11.1
Webpack: 2.7.0
UglifyJs: 2.8.29

**Comment by ShukinDmitriy** [comment]
@t0lik Тоже столкнулся с данной проблемой в проекте с ангуляром, в итоге пришлось подключить без минификации. Если вам известно работающее решение - прошу сообщить.

**Comment by J4CKVVH173** [comment]
Чисто такая же проблема, проблема в минификации, после ее отключения все заработало

**Comment by dmitrijivanchenko** [comment]
У меня тоже вот не работает getCertList, именно на проде. Rails-проект, никаких минификаций явно не использую. Есть мысли, что можно с этим сделать?

**Comment by ShukinDmitriy** [comment]
> У меня тоже вот не работает getCertsList, именно на проде. При этом на dev все норм. Rails-проект, используется гем uglifier. Есть мысли, что можно с этим сделать?

я у себя в проекте на angular переписал всю работу с крипто-про на type script. Генератор из-за которого возникает проблема тупо выкинул, да получилось не так красиво, зато работает. Если интересно - могу оформить пакетиком в npm

**Comment by dmitrijivanchenko** [comment]
@ShukinDmitriy, был бы очень признателен за пакет npm)

**Comment by dmitrijivanchenko** [comment]
потыркал гем, нашел, что в этом фрагменте проблема:

	                     certs = 'yield' + certs.Find(
	                         cadesplugin.CAPICOM_CERTIFICATE_FIND_EXTENDED_PROPERTY,
	                         cryptoConstants.PropId.CAPICOM_PROPID_KEY_PROV_INFO
	                     );
После него в минифицированном файле переменная "certs" возвращается строкой, когда должна быть объектом. В неминифицированном js все ок. Такое ощущение, что просто синтаксис преобразуется криво. Пробовал убрать этот кусок, но получилось добиться работы этого блока только заменив этот кусок на:

console.log(certs);

. Но если его убирать/заменять, стало быть сертификаты без закрытого ключа не будут отброшены?

**Comment by ShukinDmitriy** [comment]
> @ShukinDmitriy, был бы очень признателен за пакет npm)

https://www.npmjs.com/package/crypto-pro-ts

**Comment by dmitrijivanchenko** [comment]
@ShukinDmitriy, Спасибо!

**Comment by vgoma** [comment]
@t0lik, @J4CKVVH173 в последней версии проблема ушла. В примерах с angular/react используется webpack с минификацией и без.

@dmitrijivanchenko,  @ShukinDmitriy текущий проект переписан на typescript с версии 2.
