### ISSUE TITLE
Вопрос по методу createAttachedSignature

### ISSUE THREAD

**Issue by mikrob24RUS** [vgoma/crypto-pro#111]
Здравствуйте!
Спасибо большое за Вашу библиотеку!!!
Вызывая метод createAttachedSignature, передавая в него отпечаток сертификата, которым необходимо подписать файл, на выходе получаю подписанный файл, в который включён не только сертификат подписанта, но и все сертификаты из цепочки доверия.
Можно ли как-то избежать попадания в подписанный файл, сертификатов из цепочки доверия, оставив только сертификат самого подписанта?
Заранее спасибо!

**Comment by vgoma** [comment]
@mikrob24RUS добрый день. Такой опции плагин Крипто ПРО не предоставляет:
https://cpdn.cryptopro.ru/content/cades/plugin-methods.html
<img width="1506" alt="Screenshot 2023-01-08 at 12 00 00" src="https://user-images.githubusercontent.com/4262685/211188229-4331c726-1f7a-467a-97a6-943506aa12e7.png">

Насколько понимаю, это необходимо для корректной проверки подлинности подписи, тк если будет включен только сертификат подписанта, то не будет понятно почему ему можно доверять.
