### ISSUE TITLE
Возможно ли декодировать dataBase64 c помощью подписи?

### ISSUE THREAD

**Issue by Trebushnoi** [vgoma/crypto-pro#12]
Спасибо за проект!

Скажите, есть ли возможность декодировать данные в dataBase64, используя подпись? Или можно ли вытащить приватный ключ сертификата и декодировать сообщение самому?

**Comment by vgoma** [comment]
@Trebushnoi вопрос выходит за рамки пакета, и не совсем понимаю связи между двумя вопросами, но подпись бывает отделенная и совмещенная. Доступ к подписываемым данным обычно не является проблемой, тк зачем скрывать подписываемые данные? Будь они зашифрованы в base64 или нет. Закрытый ключ исходя из его названия извлечь нельзя. Однако шифрование алгоритмом base64 является двусторонним. И любые данные можно как зашифровать, так и расшифровать.

В любом случае, нет ничего невозможного) если вы найдете способ, закиньте PR.
