### ISSUE TITLE
Подпись нешифрованных документов

### ISSUE THREAD

**Issue by dmitrijivanchenko** [vgoma/crypto-pro#13]
Подскажите, пожалуйста, есть ли возможность подписывать строки без перевода их в base64?
Если да, то можно пример. К примеру, мне нужно подписать xml-файл.

Заметил, что проблема появляется, только если в строке есть некоторые символы (например '_' или '<'. Ошибка: "Не удалось установить настройки для подписи: Internal error. (0x80092002)"

Спасибо!

**Comment by vgoma** [comment]
Перевод в base64 необходим для передачи бинарных данных:
http://cpdn.cryptopro.ru/content/cades/content-encoding.html

См. разделы:
- "Особенности работы с бинарными данными"
- "Особенности работы с документами XML, кодировки которых отличны от UTF-8"

XML файл - это набор символов, который так же можно преобразовать в base64. Только стоит помнить про проблемы с кириллицей.
