### ISSUE TITLE
Не подписываются файлы размером > 50 мб - ошибка Lost connection to extension

### ISSUE THREAD

**Issue by VdovinAlexey** [vgoma/crypto-pro#134]
Не подписываются файлы размером > 50 мб - ошибка Lost connection to extension
Браузер хром.
В консоль:
Uncaught Error: Message length exceeded maximum allowed length.
at content.js:12:13
{type: 'error', requestid: 163, message: 'Lost connection to extension'}main.6dee3ce5.js:1 {type: 'error', requestid: 163, message: 'Lost connection to extension'}

аналогичная ситуация
https://www.crypto-pro.ru/forum2/default.aspx?g=posts&t=20814
информация с решением для cadesplugin_api.js 

но у нас в проекте используется именно npm пакет :(

**Comment by VdovinAlexey** [comment]
и в примере жестское ограничение прописано
"Файл для подписи не должен превышать 25МБ"
как быть если нужно подписать файл 150 мегабайт?

**Comment by vgoma** [comment]
@VdovinAlexey 
https://support.cryptopro.ru/index.php?/Knowledgebase/Article/View/213/12/ogrnichenie-n-rzmer-podpisyvemogo-fjjl-v-bruzere
