### ISSUE TITLE
Остановить поддержку bower

### ISSUE THREAD

**Issue by emcpow2** [vgoma/crypto-pro#137]
Пакетный менеджер bower больше не поддерживается авторами, его разработка прекратилась.

На официальном сайте рекомендуется перейти на другие менеджеры пакетов - yarn, npm.

Чтобы уменьшить стоимость сопровождения `crypto-pro` лучше удалить все с ним связанное в этом репозитории.

**Comment by vgoma** [comment]
Поддержка [Bower была добавлена](https://github.com/vgoma/crypto-pro/issues/6) в 2017-м, когда он уже потерял популярность. Тем не менее, люди [продолжают его использовать](https://npmcharts.com/compare/bower?minimal=true). Подумаю об отказе от него в будущей мажорной версии.
