### ISSUE TITLE
Реализация возможности расшифровки строки с помощью Private key сертификата

### ISSUE THREAD

**Issue by Kirrrusha** [vgoma/crypto-pro#138]
Столкнулся с проблемой что нужно расшифровывать полученную строку с помощью закрытого ключа сертификата пользователя в байты (или сразу в Base64), есть ли такая возможность у пакета или планируется расширение в данную сторону?

**Comment by vgoma** [comment]
Возможности нет, и не планируется, так как обычно для таких операций используются десктопные криптопровайдеры, которые обладают более высоким уровнем интеграции с аппаратными компонентами операционных систем и обеспечивают защищенную среду при выполнении криптографических операций с закрытыми ключами. Попытка переноса подобного функционала в браузерную среду сопряжена с множеством существенных технических сложностей, затраты на преодоление которых должны быть чем-то оправданы.
