### ISSUE TITLE
Метод объекта сертификата isValid вернул false

### ISSUE THREAD

**Issue by posadvladimir** [vgoma/crypto-pro#141]
Для всех тестовых сертификатов, выпущенных на сайте "Крипто Про", метод isValid возвращал true. Для рабочего сертификата, который находится в сроке действия и который не был отозван, метод вернул false. Из-за какого параметра в сертификате могло такое произойти? Был бы благодарен, если бы описали, как осуществляется проверка в данном методе.

**Comment by vgoma** [comment]
Основной вопрос лежит за рамками этого проекта, однако рабочий сертификат может считать не валидным из-за некорректно построенной цепочки доверия в системе. Проверьте правильность установки промежуточных сертификатов УД.

Проверка осуществляется довольно просто, [путем вызова метода](https://github.com/vgoma/crypto-pro/blob/master/src/api/certificate/isValid.ts#L19), предоставляемого Cades Plugin-ом.

Об особенностях тестовых сертификатов, выпускаемых на сайте "Крипто Про" мне не известно.
