### ISSUE TITLE
"Ошибка при подписании данных"

### ISSUE THREAD

**Issue by Tsvetkraft** [vgoma/crypto-pro#146]
С некоторых клиентских машин приходит такая ошибка в логи. По коду видно, что это из вызова

`cadesSignedData.SignHash(cadesHashedData, cadesSigner, cadesplugin.CADESCOM_PKCS7_TYPE)`

Можете подсказать, куда дальше смотреть для диагностики проблемы?

**Comment by IlyaUhlianitsa** [comment]
До вчерашнего дня всё работало, а сегодня стал получать такую же ошибку.
![image](https://github.com/vgoma/crypto-pro/assets/14961737/39635cbc-6d32-4580-9fa4-624bb8256240)

В чём может быть дело и как исправить?
@Tsvetkraft удалось решить?
@vgoma помогите, пожалуйста.

**Comment by IlyaUhlianitsa** [comment]
У меня закончилась лицензия Крипто-Про, поэтому не работает :)

**Comment by vgoma** [comment]
Пакет старается дать максимально понятное, общее описание ошибки + текст оригинального сообщения, если нужно больше деталей. Но согласен, некоторые описания ошибок, приходящие от Крипто-Про бывают совсем не информативны. Даже описание одной и той же ошибки может отличаться от системе к системе.
