### ISSUE TITLE
Не удается получить список сертификатов ($r.Find is not a function)

### ISSUE THREAD

**Issue by SolDier2018** [vgoma/crypto-pro#148]
Подскажите в чем может быть проблема? Если нужно предоставить дополнительные вводные, напишите, пожалуйста.

<img width="376" alt="image" src="https://github.com/vgoma/crypto-pro/assets/37969534/5eacd041-5bb9-48dc-8b31-85d4196642ee">

На сколько я понял из файла `crypto-pro_dynamicFn.js` не удается получить список сертификатов, но по какой причине не понимаю.

**Comment by SolDier2018** [comment]
Ругается на строчку `$r = _generateCadesFn_1.__cadesAsyncToken__ + $r.Find(cadesplugin.CAPICOM_CERTIFICATE_FIND_EXTENDED_PROPERTY, constants_1.CAPICOM_PROPID_KEY_PROV_INFO),`

**Comment by MayFlit** [comment]
> Подскажите в чем может быть проблема? Если нужно предоставить дополнительные вводные, напишите, пожалуйста.
> 
> <img alt="image" width="376" src="https://private-user-images.githubusercontent.com/37969534/330789354-5eacd041-5bb9-48dc-8b31-85d4196642ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0OTU3NDcsIm5iZiI6MTcxOTQ5NTQ0NywicGF0aCI6Ii8zNzk2OTUzNC8zMzA3ODkzNTQtNWVhY2QwNDEtNWJiOS00OGRjLThiMzEtODVkNDE5NjY0MmVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDEzMzcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwMGY1MjY1NzI4MDc3M2UyMDI3ODhiYmE0ZDQ1MDQ0OGI1NmY1NGUwOWYxMmE5MThiMDBlZTYwOWZhYjk0OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NKRrTxZ2qi0Ur3pzUtdrroLB4lcT2Fu6TGUTvlU8QEA">
> На сколько я понял из файла `crypto-pro_dynamicFn.js` не удается получить список сертификатов, но по какой причине не понимаю.

Удалось решить этот момент? У меня похожая ошибка, работать это как я понял перестало как раз около месяца назад.
Причем на локально развернутом проекте все нормально, а если уже на VPS заходить, то такая ошибка.

![image](https://github.com/vgoma/crypto-pro/assets/62111365/751849d3-fd52-4c71-8c1c-123f7c1d3b50)

**Comment by MayFlit** [comment]
![image](https://github.com/vgoma/crypto-pro/assets/62111365/9076ed67-ab0a-4a61-8cb9-b534aaaf8f2a)
Дополнительно логнул ошибку, похоже имеется проблема с интеграцией с плагином CryptoPro для браузера.

**Comment by SolDier2018** [comment]
@MayFlit Мне удалось выяснить что проблема возникала после того как я в проект заносил новую зависимость.
Пораскуривав немного исходный код, обнаружил что во многих методах присутствует метод `eval()`, а это очень небезопасная штука.

В итоге я написал свою либу без использования `eval()` и вроде как все работает.

Если подытожить, проверьте все новые зависимости, возможно это сможет вам помочь.

**Comment by SolDier2018** [comment]
> ![image](https://private-user-images.githubusercontent.com/62111365/343814277-9076ed67-ab0a-4a61-8cb9-b534aaaf8f2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NjMxNzIsIm5iZiI6MTcxOTU2Mjg3MiwicGF0aCI6Ii82MjExMTM2NS8zNDM4MTQyNzctOTA3NmVkNjctYWIwYS00YTYxLThjYjktYjUzNGFhYWY4ZjJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDA4MjExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxOTA1Y2M1Y2EzN2E3NTk1YmQ3ZDRhYjAwMWEwOWQwZTA5ZmMyNDdhODgwNmJiYmEzNWE5ZmFhNjFlNWZlYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5LWZZkmMCtCYljFbvInFjWvCDZef6QH2klLRxB3F8dw) Дополнительно логнул ошибку, похоже имеется проблема с интеграцией с плагином CryptoPro для браузера.

Вот эти ошибки они просто в `catch` ловятся, то есть если какая-то зависимость сделает инъекцию при сборке в `eval()`, то логика будет нарушена и библиотека ломается.

**Comment by vgoma** [comment]
Когда-нибудь `eval()` пропадет из библиотеки:
https://github.com/vgoma/crypto-pro/issues/149#issuecomment-2130717854

**Comment by MayFlit** [comment]
> @MayFlit Мне удалось выяснить что проблема возникала после того как я в проект заносил новую зависимость. Пораскуривав немного исходный код, обнаружил что во многих методах присутствует метод `eval()`, а это очень небезопасная штука.
> 
> В итоге я написал свою либу без использования `eval()` и вроде как все работает.
> 
> Если подытожить, проверьте все новые зависимости, возможно это сможет вам помочь.

Спасибо, видел как раз вашу библиотеку, но решил, что раз уж все равно копаться в дебрях, то сам реализую нужные мне функции на основе API плагина. И это в целом помогает, не все дописал еще, но проблема действительно была в библиотеке. 
Разве что до сих пор не понимаю почему у меня локально эта ошибка не воспроизводится, а только на удаленном сайте.

**Comment by SolDier2018** [comment]
> > @MayFlit Мне удалось выяснить что проблема возникала после того как я в проект заносил новую зависимость. Пораскуривав немного исходный код, обнаружил что во многих методах присутствует метод `eval()`, а это очень небезопасная штука.
> > В итоге я написал свою либу без использования `eval()` и вроде как все работает.
> > Если подытожить, проверьте все новые зависимости, возможно это сможет вам помочь.
> 
> Спасибо, видел как раз вашу библиотеку, но решил, что раз уж все равно копаться в дебрях, то сам реализую нужные мне функции на основе API плагина. И это в целом помогает, не все дописал еще, но проблема действительно была в библиотеке. Разве что до сих пор не понимаю почему у меня локально эта ошибка не воспроизводится, а только на удаленном сайте.

У меня так же ошибка воспроизводилась только в собранной версии, при локальной разработке все корректно работало. Других причин, кроме как `eval()` я не нашел. У меня сборщик даже ругался и предупреждал что присутствует этот метод
