### ISSUE TITLE
Библиотеку невозможно использовать на сайтах с включенной Content Security Policy политикой (нужен unsafe-eval)

### ISSUE THREAD

**Issue by FractalizeR** [vgoma/crypto-pro#149]
Добрый день.

Ужесточаем безопасность кода на нашем ресурсе и заметили, что без указания unsafe-eval на сайте при использовании библиотеки [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src) включить не удается. Причина в том, что в коде библиотеки используются вызовы `eval()`. Есть ли возможность от них уйти? Вроде бы ничего не мешает их развернуть в нормальный вызов.

**Comment by vgoma** [comment]
Доброго времени суток.

Библиотека использует вызовы `eval()` по историческим причинам. КриптоПРО Browser Plugin в более ранних версиях браузеров предоставлял API в синхронном стиле (без необходимости использовать генераторы). К сожалению, старые браузеры не в состоянии правильно распарсить и выполнить JavaScript файл, если в нем присутствует синтаксис генераторов. Поэтому, для универсальности, библиотека в рантайме генерирует синтаксически правильное тело функции перед выполнением, в зависимости от возможностей браузера и API, предоставляемого КриптоПРО Browser Plugin. Чтобы лучше понять о чем я, можно [взглянуть на тесты](https://github.com/vgoma/crypto-pro/blob/master/src/helpers/_generateCadesFn.test.ts). Подключать JavaScript файл с нужным синтаксисом динамически к HTML странице усложнило бы использование библиотеки и сильно зависело бы от способов сборки и доставки приложения пользователям в браузер.

На данный момент, популярность браузеров без поддержки генераторов сильно упала, и есть планы уйти от `eval()` в следующей мажорной версии.

**Comment by pumano** [comment]
в последней версии (2.3.8) библиотека больше не использует eval.

**Comment by iAchilles** [comment]
Спасибо!

**Comment by pustart** [comment]
@FractalizeR Сделал форк с обновленным cadesplugin, а также убрал eval для корретной работы с CSP (self)
https://github.com/pustart/crypto-pro-csp-compatible?tab=readme-ov-file
