### ISSUE TITLE
Запуск Angular примера в IE 11 

### ISSUE THREAD

**Issue by tazaryoot** [vgoma/crypto-pro#15]
Склонировал проект. Запустил по readme пример на ангуляре. В хроме все ок, а в IE 11 ошибка в консоли 
![image](https://user-images.githubusercontent.com/1438479/78254035-fe498380-74fd-11ea-876f-58f51550208d.png)
перешел в указанную строку 
![image](https://user-images.githubusercontent.com/1438479/78254133-1e794280-74fe-11ea-9214-339a297cbef3.png)
IE же не понимает class. Что делать в этой ситуации?

**Comment by vgoma** [comment]
@tazaryoot похоже, что в примере с Angular не хватает полифилла для запуска в режиме разработки, тк в продакшн режиме все работает. Официально в Angular заявлена поддержка IE11 для проектов, использующих CLI:
https://angular.io/guide/browser-support

Однако в режиме разработки в IE11 у меня не показывается даже сама ошибка:
![image](https://user-images.githubusercontent.com/4262685/78275632-863d8680-751a-11ea-9f5e-0c1902ff58dc.png)

В примерах с React (в обоих режимах) и тэгом скрипт такой проблемы нет.

Попробую посмотреть как это обойти когда будет время.

**Comment by tazaryoot** [comment]
что бы в IE 11 работал режим разработки надо в tsconfig в поле target указать ES5
![image](https://user-images.githubusercontent.com/1438479/78278651-04039100-751f-11ea-8524-13aff42e116a.png)

**Comment by vgoma** [comment]
@tazaryoot спасибо за апдейты, но на данный момент, если вы сгенерируете чистый проект при помощи Angular CLI, он не будет работать в IE11 **в режиме разработки**.

Angular CLI [не поддерживает](https://github.com/angular/angular-cli/issues/14455) IE11 в этом режиме.

Эта проблема не уникальна для Angular. У React есть [те же проблемы](https://github.com/facebook/create-react-app/issues/5336).

Предложенный воркэраунд, имеет свои подводные и заявлен контрибьюторами Angular CLI как не рекомендованный, тк меняет способ подгрузки полифиллов. Он так же не имеет большого смысла, тк если есть необходимость проверки работы в старых IE, надо запускать пример **в режиме продакшн**.

Цель примеров данного пакета - показать работу не кастомизируя процесс сборки который идет из коробки у популярных фреймворков. Поэтому если вам необходима поддержка IE11 **в режиме разработки**, подстраивайте процесс сборки под свой проект.

**Comment by tazaryoot** [comment]
У меня проблема так же при билде для прода. (ангуляр 8)
![image](https://user-images.githubusercontent.com/1438479/78422895-56ea5f00-766b-11ea-8174-f1071d3463d4.png)
![image](https://user-images.githubusercontent.com/1438479/78422911-72ee0080-766b-11ea-87fd-8be42d978529.png)
Я поэтому пробовал и на вашем примере.
Я подозреваю, что в билд у меня попадает скрипт ./lib/crypto-pro.js, а не ./dist/crypto-pro.js

**Comment by vgoma** [comment]
это как раз из-того, что вы меняли стандартный процесс сборки и у вас не работает дифференцированная подгрузка бандлов. проверил на 8 ангуляре (@angular/cli@8.3.26), все работает.

**Comment by tazaryoot** [comment]
Для сборки на прод я все возвращал обратно

**Comment by vgoma** [comment]
скрин с 8 ангуляром в продакшн режиме:
![image](https://user-images.githubusercontent.com/4262685/78451423-3a135300-768e-11ea-9f76-b3391e591526.png)

**Comment by tazaryoot** [comment]
Да я вам верю))
Просто в моем случае в IE 11 прод сборка со стандартным tsconfig не работает.

**Comment by vgoma** [comment]
у вас процесс сборки отличается, вам нужно либо дополнительно транспилировать библиотеку, либо использовать ее из папки dist (но это грязный путь))

**Comment by tazaryoot** [comment]
я не менял процесс сборки все стандартно. Я не особо в этом шарю, чтобы что то менять

**Comment by vgoma** [comment]
Обратите внимание, что `ng serve --prod=true` и `ng build` это не одно и то же. В примере с ангуляром используется статический сервер, эмулирующий реальный продакшн сервер, работающий на реально собранном приложении, а не на `ng serve --prod=true`.

**Comment by tazaryoot** [comment]
У меня именно ng build

"build": "ng build --prod --output-path=../../www/f/dist/ --delete-output-path false  --build-optimizer"

Сервер на bitrix

**Comment by vgoma** [comment]
у меня и так работает)
```bash
> ng build --prod

Generating ES5 bundles for differential loading...
ES5 bundle generation complete.

chunk {0} runtime-es2015.0811dcefd377500b5b1a.js (runtime) 1.45 kB [entry] [rendered]
chunk {0} runtime-es5.0811dcefd377500b5b1a.js (runtime) 1.45 kB [entry] [rendered]
chunk {2} polyfills-es2015.1f913f16a2d346cc8bdc.js (polyfills) 36.1 kB [initial] [rendered]
chunk {3} polyfills-es5.1a3c78b07cd6f16c6e9a.js (polyfills-es5) 129 kB [initial] [rendered]
chunk {1} main-es2015.4515cd8d9a7c523653b5.js (main) 245 kB [initial] [rendered]
chunk {1} main-es5.4515cd8d9a7c523653b5.js (main) 283 kB [initial] [rendered]
chunk {4} styles.3ff695c00d717f2d2a11.css (styles) 0 bytes [initial] [rendered]
Date: 2020-04-04T15:22:39.407Z - Hash: 24926550d83b524e44f6 - Time: 56737ms
```

![image](https://user-images.githubusercontent.com/4262685/78454622-d98e1100-76a1-11ea-89ff-eff93defb185.png)

**Comment by tazaryoot** [comment]
Хорошо вам. У меня увы не так(

**Comment by tazaryoot** [comment]
Обновил ангуляр до 9.1 и заработало все
