### ISSUE TITLE
Ошибка при проверке подписи

### ISSUE THREAD

**Issue by Chepa** [vgoma/crypto-pro#17]
Скачал новую версию, запустил пример crypto-pro/examples/script-tag/. Подпись отличается от той что создаётся здесь: https://www.cryptopro.ru/sites/default/files/products/cades/demopage/cades_bes_sample.html

```
{
  "cadesVersion": "2.0.13771",
  "cspVersion": "5.0.11455",
  "isValidSystemSetup": true
}
```

**Comment by Chepa** [comment]
Решил проблему таким преобразованием в base64:
```
btoa(encodeURIComponent(str).replace(/%([0-9A-F]{2})/g,
                function toSolidBytes(match, p1) {
                    return String.fromCharCode('0x' + p1);
                }))
```

**Comment by vgoma** [comment]
@Chepa в каком смысле "отличается"? сама подпись или способ ее создания?
полезная информация:
https://www.cryptopro.ru/faq/razlichnaya-podpis-dlya-odnikh-i-tekh-zhe-dannykh

**Comment by Chepa** [comment]
@vgoma при попытке подписать строку OJWVWTMPHJYMZCNPASBUOOISWQYHOX получил разный результат, подписи отличаются по длине.

**Comment by vgoma** [comment]
@Chepa как проверяете подпись? почему считаете, что она должна совпадать? слышали ли про открепленную/совмещенную подпись?

**Comment by vgoma** [comment]
В примере, с которым вы сравниваете используется **совмещенная** подпись, а в `crypto-pro/examples/script-tag/` используется **отделенная**. Обратите внимание на [третий параметр](https://github.com/vgoma/crypto-pro/blob/master/src/api/createSignature.ts). Проверил на вашей строке, если сделать совмещенную подпись, результат будет валидный.

**Comment by Chepa** [comment]
@vgoma спасибо большое! разобрался!
