### ISSUE TITLE
Проверка открепленной подписи и подписанного файла.

### ISSUE THREAD

**Issue by Galeups** [vgoma/crypto-pro#18]
Добрый день.
Подскажите пожалуйста, я так понял в реализации для Angular нет функционала проверки открепленнойподписи. Планируется ли добавление данного функционала?
Заранее спасибо.

**Comment by vgoma** [comment]
Здравствуйте. В планах нет, тк целесообразнее проверять подпись средствами КриптоПРО на сервере. Но был бы не против корректно работающей реализации pull-request'ом.
