### ISSUE TITLE
Вычисление hash

### ISSUE THREAD

**Issue by dmoskin** [vgoma/crypto-pro#2]
Виталий, здравствуйте.
Подскажите, можно ли, используя, Вашу библиотеку получить хэш файла?

**Comment by vgoma** [comment]
@dmoskin привет. Есть подводные камни вычисления хэша файла на клиенте.

Они сводятся к тому, что нет гарантии получить идентичный хэш одного и того же файла на клиенте и сервере. Например, в IE8 проблемы начинаются с получения контента файла (прямо в браузере), и заканчиваются тем, что отсутствует официальная реализация механизма шифрования в base64 (window.btoa).

Поэтому стоит вычислять хэш файла на сервере, отправлять его на клиент и там уже подписывать. Конечно с правовой точки зрения у конечного пользователя могут быть сомнения, относительного того, не подменяет ли контент файла в процессе вычисления хэша сервер. Но если он захочет это проверить, то всегда сможет взять подписываемый хэш файла и сверить его с результатом вычисления на каком-нибудь другом ресурсе.

**Comment by Bykiev** [comment]
@vgoma, здравствуйте, предстоит работать с подписью xml в браузере, в [примере ](https://www.cryptopro.ru/sites/default/files/products/cades/demopage/cades_xmldsig_sample.html) происходит подпись с вычислением хэша по алгоритму в ключе (интересует ГОСТ 34.10-2012 256/512 бит), возможно ли повторить этот пример с использованием вашей библиотеки?
