### ISSUE TITLE
При попытке запустить билд приложения в ie, приложение крашится

### ISSUE THREAD

**Issue by Intellcet** [vgoma/crypto-pro#25]
Если установить пакет как обычную зависимость в проект `npm i crypto-pro`, а потом попытаться собрать проект при помощи вебпака 4 + бабеля 7, в билд попадают нотации es6 - это class и yield. Думается мне, это можно пофиксить, если в package.json вместо `"main": "./lib/crypto-pro.js" и "types": "./lib/crypto-pro.d.ts"` записать `"main": "./dist/crypto-pro.js" и "types": "./dist/crypto-pro.d.ts"`, потому что при копировании файлов из dist в lib, проект собирается без ошибок и запускается в ie

@vgoma

**Comment by vgoma** [comment]
@Intellcet не нужно ничего фиксить.

Попробуйте [пример с React](https://github.com/vgoma/crypto-pro#react-es-modules--javascript). Он как раз использует react-scripts с Webpack 4 и Babel 7:
![Screenshot 2020-08-08 at 12 20 22](https://user-images.githubusercontent.com/4262685/89706834-f26d4280-d971-11ea-92c2-5bbaeccea608.png)

![Screenshot 2020-08-08 at 12 29 26](https://user-images.githubusercontent.com/4262685/89706969-006f9300-d973-11ea-86e9-3e7e0b8ab2cc.png)
