### ISSUE TITLE
Сборка проекта в минифицированной версии в одном файле

### ISSUE THREAD

**Issue by NicoBurno** [vgoma/crypto-pro#3]
@vgoma могу я настроить Webpack в этом проекте на сборку минифицированной версии прогнанной через Babel?
Спрашиваю потому, что кроме вас пока проектом никто не занимается.

**Comment by NicoBurno** [comment]
Сделал PR #4 
В один файл собирать не стал - ибо судя по коду вы специально разделили реализацию на два варианта и подгружаете нужный вариант асинхронно.
Можете подсказать почему вы приняли именно такое решение? Почему бы не объединить код и выбирать между двумя вариантами "налету"?

**Comment by vgoma** [comment]
@NicoBurno когда занимался сборкой этого модуля не было нормального способа минифицировать асинхронные функции. Поддерживаю оба варианта из-за того, нельзя допустить чтобы скрипт с синтаксическими конструкциями асинхронных функций попал в браузер, который их не поддерживает, т. к. скрипт упадет еще до его выполнения (на этапе парсинга кода) Не вижу надобности полифилить то, что и так работает. Посмотрел PR. Вы добавили кучу зависимостей + завязались на глобально установленный webpack + не зафиксировали жестко версии ваших модулей. После всего этого мой проект просто не собирается.

**Comment by NicoBurno** [comment]
@vgoma по поводу жесткой фиксации - справедливо. Для стабильности зависимости стоит зафиксировать. Но вот в остальном:

- **webpack** завязан не на глобальную область видимости. Если сомневаетесь - выполните команду **[npm bin](https://docs.npmjs.com/cli/bin)** из рутовой директории проекта. Скорее всего вы просто не выполнили **npm update**. Скиньте лог ошибки и я помогу с ней разобраться
- Иметь оба варианта - это не самое лучшее решение. Приходится тянуть лишний файл асинхронно и к тому же мы имеем два идентичных исходника. Babel же нам позволит избежать "синтаксических ошибок" на этапе парсинга.

По минификации: у вас были сложности с минификацией генераторов или же какие-то другие?

**Comment by NicoBurno** [comment]
Проблема была действительно в зависимостях - я не заметил **npm-shrinkwrap.json**
#5 решает эту проблему

**Comment by vgoma** [comment]
@NicoBurno идея с единым исходником очень здравая, я ее поддерживаю.

Обратите внимание на способ работы с данными:
Асинхронная версия: `yield oAttrs.propset_Value(clientTime);`
Синхронная версия: `oAttrs.Value = clientTime;`
Как будем решать проблему?

После обновления все собралось, но примеры теперь не работают. Вы проверяли в заявленных в README браузерах? Ошибка доступа к объекту.
Chrome 58: `Cannot read property 'call' of undefined`
Firefox 53: `window.CryptoPro is undefined`
