### ISSUE TITLE
Не видит сертификаты с USB накопителя

### ISSUE THREAD

**Issue by hazratgs** [vgoma/crypto-pro#31]
Приветствую, есть проблема, библиотека не видит сертификат с usb накопителя, демо на оф сайте crypto-pro видит....
Единственную разницу, которую я заметил в вашей библиотеки и кодом на официальном сайте, это то что у вас указано откуда брать сертификаты:
`cadesStore.Open(cadesplugin.CAPICOM_CURRENT_USER_STORE, cadesplugin.CAPICOM_MY_STORE, cadesplugin.CAPICOM_STORE_OPEN_MAXIMUM_ALLOWED))`

Тогда как на оф сайте просто:
`cadesStore.Open()`

Что можете посоветовать?

**Comment by vgoma** [comment]
@hazratgs доброго дня.
Данный пакет работает с сертификатами, установленными в хранилище **текущего пользователя**:
![Screenshot 2020-10-24 at 20 49 30](https://user-images.githubusercontent.com/4262685/97088580-84fcb400-163a-11eb-8828-511d6a8f6073.png)

USB носитель тут скорее всего не играет роли, тк он подключается, для обеспечения доступа СКЗИ к закрытому ключу.

Попробуйте локально [запустить исходники](https://github.com/vgoma/crypto-pro#%D1%82%D0%B5%D0%BC-%D0%BA%D1%82%D0%BE-%D1%85%D0%BE%D1%87%D0%B5%D1%82-%D0%BF%D0%BE%D0%BC%D0%BE%D1%87%D1%8C) и поиграться с реализацией, чтобы локализовать проблему.

**Comment by lemonspb** [comment]
> Приветствую, есть проблема, библиотека не видит сертификат с usb накопителя, демо на оф сайте crypto-pro видит....
> Единственную разницу, которую я заметил в вашей библиотеки и кодом на официальном сайте, это то что у вас указано откуда брать сертификаты:
> `cadesStore.Open(cadesplugin.CAPICOM_CURRENT_USER_STORE, cadesplugin.CAPICOM_MY_STORE, cadesplugin.CAPICOM_STORE_OPEN_MAXIMUM_ALLOWED))`
> 
> Тогда как на оф сайте просто:
> `cadesStore.Open()`
> 
> Что можете посоветовать?

Здравствуйте, возник точно такой же вопрос, не удалось решить?

**Comment by hazratgs** [comment]
@lemonspb удалось, попытаюсь отправить pull request или приведу здесь

**Comment by hazratgs** [comment]
`
import { Certificate, CadesCertificate } from 'crypto-pro'

export const extractCommonName = (subjectName: string): string | undefined =>
  subjectName.match(/CN=(.+?)(?:,|$)/)?.[1]

export const updateCertificated = async (oStore: any, certificates: Certificate[]) => {
  const scope = await oStore.Certificates
  const countCertificates = await scope.Count

  if (!countCertificates) throw new Error('Certificate not found')

  for (let i = 1; i <= countCertificates; i++) {
    const cadesCertificate: CadesCertificate = await scope.Item(i)

    const certificate = new Certificate(
      cadesCertificate,
      String(extractCommonName(await cadesCertificate.SubjectName)),
      await cadesCertificate.IssuerName,
      await cadesCertificate.SubjectName,
      await cadesCertificate.Thumbprint,
      await cadesCertificate.ValidFromDate,
      await cadesCertificate.ValidToDate,
    )

    const isValid = await certificate.isValid()
    const isExistCertificate = certificates.some((item) => item.thumbprint === certificate.thumbprint)

    if (isValid && !isExistCertificate) {
      certificates.push(certificate)
    }
  }
}

export const getUserCertificates = async (): Promise<Certificate[]> => {
  let oStore
  const certificates: Certificate[] = []

  try {
    oStore = await window.cadesplugin.CreateObjectAsync('CAdESCOM.Store')
  } catch (err) {
    console.error('Ошибка при получение доступа к хранилищу сертификатов', err)
  }

  try {
    await oStore.Open()
    await updateCertificated(oStore, certificates)
  } catch (err) {
    console.error(err)
    throw new Error('Ошибка получения списка сертификатов')
  }

  try {
    await oStore.Open(window.cadesplugin.CADESCOM_CONTAINER_STORE)
    await updateCertificated(oStore, certificates)
  } catch (err) {
    console.error(err)
    throw new Error('Ошибка получения списка сертификатов не установленных в хранилище')
  }

  return certificates
}

`

**Comment by lemonspb** [comment]
> @lemonspb удалось, попытаюсь отправить pull request или приведу здесь

тоже только что разобрался нужно было добавить в стор эту константу 		  	 store.Open(cadesplugin.CADESCOM_CONTAINER_STORE);

**Comment by hazratgs** [comment]
> > @lemonspb удалось, попытаюсь отправить pull request или приведу здесь
> 
> тоже только что разобрался нужно было добавить в стор эту константу store.Open(cadesplugin.CADESCOM_CONTAINER_STORE);

Да, но к сожалению средствами самой библиотеки это нельзя решить, пришлось свой метод написать
