### ISSUE TITLE
Создание открепленной подписи для файла

### ISSUE THREAD

**Issue by serj7220** [vgoma/crypto-pro#32]
Добрый день, Виталий.
 
Изучаю Вашу библиотеку. Отличная библиотека, очень удобная в использовании.
Подскажите пожалуйста, можно ли при помощи Вашей библиотеки создавать открепленную подпись для файла?

Я такую возможность, к сожалению, не нашел в описанных методах объекта cryptoPro. И если такая возможность есть, то как ее можно реализовать?
 
За ранее спасибо.

**Comment by vgoma** [comment]
@serj7220 приветствую, спасибо.

Метод [createHash](https://github.com/vgoma/crypto-pro/blob/master/src/api/createHash.ts#L14) умеет принимать в качестве шифруемого сообщения бинарные данные ([ArrayBuffer](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer)). Поэтому вы можете сделать это так:
```javascript
document.getElementById('messageFile').addEventListener('change', function(event) {
  var file = event.target.files[0],
    fileReader = new FileReader();

  fileReader.onload = function () {
    window.cryptoPro.createHash(this.result)
      .then(function (messageHash) {
        window.cryptoPro.createDetachedSignature(/* thumbprint ,*/ messageHash);
      });
  };

  fileReader.readAsArrayBuffer(file);
});
```

При этом надо помнить, что FileReader поддерживается в IE10+.

Дополнил [пример с тэгом скрипт](https://github.com/vgoma/crypto-pro#%D1%82%D1%8D%D0%B3-script-umd) чтобы смогли поиграться вживую:
![Screenshot 2020-11-07 at 22 16 39](https://user-images.githubusercontent.com/4262685/98449727-f95d4a00-2146-11eb-83e1-e00af619a12c.png)

**Comment by serj7220** [comment]
Спасибо, все сработало.
