### ISSUE TITLE
Отделенная подпись не создается.

### ISSUE THREAD

**Issue by nomhoi** [vgoma/crypto-pro#35]
Добрый день!

Пробую библиотеку на Ubuntu, Chrome. 
Пробую пример script-tag.
Отделенная подпись не создается.  Хэш создается.

Информация о системе:

  {
    "cadesVersion": "2.0.13642",
    "cspVersion": "5.0.11944",
    "isValidSystemSetup": true
  }

**Comment by nomhoi** [comment]
Совмещенная тоже не создается, хэш создается.

**Comment by nomhoi** [comment]
А на этой странице создается нормально:
https://www.cryptopro.ru/sites/default/files/products/cades/demopage/cades_bes_sample.html

**Comment by nomhoi** [comment]
Попробую поставить актуальную версию CSP, с ней работало, сейчас стоит последняя сертифицированная.

**Comment by vgoma** [comment]
@nomhoi вы подписываете файл или строку? Предоставьте больше информации. Конкретные данные, скриншот, текст/место ошибки.

**Comment by nomhoi** [comment]
> @nomhoi вы подписываете файл или строку? Предоставьте больше информации. Конкретные данные, скриншот, текст/место ошибки.

В примере script-tag, который присутствует в вашей библиотеке, ввожу любую строку. Пробую создать и совмещенную и отделенную подписи. Хэш создается, подписи не создаются.

В тоже время, этот пример https://www.cryptopro.ru/sites/default/files/products/cades/demopage/cades_bes_sample.html работает нормально.

Информация о системе: ос убунту 18.04, браузер хром. 
Пакеты криптопро - сертифицированные версии:
{
"cadesVersion": "2.0.13642",
"cspVersion": "5.0.11944",
"isValidSystemSetup": true
}

Поставил последние актуальные версии пакетов криптопро - работает нормально. Хэш и подписи создаются.

**Comment by vgoma** [comment]
@nomhoi если проблема все еще актуальна, давайте увидим ваш подобный скриншот:
![Screenshot 2021-02-06 at 22 38 59](https://user-images.githubusercontent.com/4262685/107128140-51cdf000-68cc-11eb-9ac6-82345c3a1e7d.png)
> такую картину вижу с попыткой создать подпись при не подключенном токене в OSX

**Comment by nomhoi** [comment]
message: "The parameter is incorrect. (0x80070057)"

**Comment by nomhoi** [comment]
На этой странице подписывает нормально: https://www.cryptopro.ru/sites/default/files/products/cades/demopage/cades_bes_sample.html

**Comment by nomhoi** [comment]
Не данный момент проблема не актуальна, с такой версией работает:
{
  "cadesVersion": "2.0.14071",
  "cspVersion": "5.0.11944",
  "isValidSystemSetup": true
}

**Comment by vgoma** [comment]
> message: "The parameter is incorrect. (0x80070057)"
> requestid: 74
> type: "error"

Это не скриншот. Не понятно, что вы подписывали и чем. Такая ошибка возвращается криптопро когда один из параметров, подаваемых на подпись не корректен.
