### ISSUE TITLE
Ошибка создание отсоединенной подписи

### ISSUE THREAD

**Issue by TomySmit** [vgoma/crypto-pro#36]
Ошибка  возникает в этом коде:
`{message: "The parameter is incorrect. (0x80070057)", requestid: 43, type: "error"}`
```
       let signature;
        try {
            signature =
                yield cadesSignedData.SignHash(cadesHashedData, cadesSigner, cadesplugin.CADESCOM_PKCS7_TYPE);
        }
        catch (error) {
            console.error(error);
            throw new Error(_extractMeaningfulErrorMessage_1._extractMeaningfulErrorMessage(error) || 'Ошибка при подписании данных');
        }
```

По данной ссылке 
[Демо плагин](https://www.cryptopro.ru/sites/default/files/products/cades/demopage/cades_bes_sample.html) создает.

Установлена последняя версия CSP, на ранних работает.

**Comment by vgoma** [comment]
@TomySmit ошибку бросает КриптоПРО. Убедитесь, что хэш, который вы передаете на подпись сгенерирован по алгоритму ГОСТ Р 34.11-2012 256 бит
