### ISSUE TITLE
Ошибка CSP "The parameter is incorrect (0x80070057)" на версии cades "2.0.13642"

### ISSUE THREAD

**Issue by ALPNP** [vgoma/crypto-pro#48]
Добрый день, @vgoma.
Спасибо за разработанную библиотеку.

Есть проблемы с подписанием XML отделенной подписью.

**Окружение**:
OS Astra Linux (Smolensk) 1.6 64bit
Browser Firefox 72.0.1 (64bit)
cadesVersion 2.0.13642
cspVersion 5.0.11998

**Воспроизведение**:
1) Получаем ArrayBuffer из XML файла
2) Передаем ArrayBuffer в функцию createHash
3) Полученный хеш и отпечаток ЭЦП передаем в функцию createDetachedSignature

**Результат**:
Подпись не создана, в консоли браузера ошибка:
"The parameter is incorrect (0x80070057)"

**Ожидаемый результат**:
Получаем подпись в формате PKCS7

**Дополнительная информация**:
Пробовали подписывать на MacOS 10.15.4 на cadesVersion 2.0.13642 (сертифицированная), получаем ошибку.
Пробовали подписывать на MacOS 10.15.4 на cadesVersion 2.0.14071, ошибки нет, подпись работает.
Версии CSP на MacOS и на Astra Linux идентичные.

Возможно Вы сталкивались с похожими проблемами, что можно предпринять в данном случае ? Не уверен что мы можем использовать версию 2.0.14071 т.к. она не сертифицирована.

Готов предоставить любую дополнительную информацию которая может потребоваться для разрешения данной проблемы.

Заранее благодарен.
С Уважением.

UPD:
Пробовали на версии CSP "5.0.11944", тоже получаем ошибку.

**Comment by ALPNP** [comment]
Пробовали на версии CSP "5.0.11944", тоже получаем ошибку.

**Comment by vokshirg** [comment]
То же самое. @ALPNP нашли решение проблемы?
`{
cadesVersion: 2.0.13292, 
cspVersion: 4.0.9842, 
isValidSystemSetup: True
OS: Windows 10
}`
Параметр задан неверно. (0x80070057)

**Comment by norguhtar** [comment]
Обновляйте cades. Я ловил ошибку на шифровании под linux. Написал в поддержку, в итоге мне дали более свежую версию где шифрование работало.

**Comment by ALPNP** [comment]
Добрый день @vokshirg. Мы решили нашу проблему, написали полностью свое решение. От данной библиотеки отказались. Ошибка "Параметр задан неверно. (0x80070057)" может появляться из-за целого ряда причин. Советую конечно обновить cades (если у вас есть возможность).

**Comment by vgoma** [comment]
Всем привет. Обновил cadesplugin_api пакета в версии 2.3.2. Если есть, что добавить в библиотеку, открывайте PR.
