### ISSUE TITLE
Синтаксическая ошибка internet explorer 10

### ISSUE THREAD

**Issue by ismagilovnail** [vgoma/crypto-pro#50]
Добрый день @vgoma 
После обновления с 2.1.0 на 2.2.0
explorer показывает ошибку на строке 2226 в файле crypto-pro.js 
---->class Certificate {

**Comment by vgoma** [comment]
https://github.com/vgoma/crypto-pro/issues/15
https://github.com/vgoma/crypto-pro/issues/25
