### ISSUE TITLE
Проверка подписи

### ISSUE THREAD

**Issue by nPaul** [vgoma/crypto-pro#7]
Реализация функции проверки ЭЦП.

Из документации cadesplugin

```
    function VerifySignature(oHashedData, sSignedMessage) {
        // Создаем объект CAdESCOM.CadesSignedData
        var oSignedData = cadesplugin.CreateObject("CAdESCOM.CadesSignedData");

        // Проверяем подпись
        try {
            oSignedData.VerifyHash(oHashedData, sSignedMessage, CADESCOM_CADES_BES);
        } catch (err) {
            alert("Failed to verify signature. Error: " + cadesplugin.getLastError(err));
            return false;
        }

        return true;
    }

```

**Comment by vgoma** [comment]
@nPaul очень хорошо. К чему он здесь?

**Comment by nPaul** [comment]
Не могли бы реализовать функции проверки ЭЦП.
Из хеша файла в base64 , в этом случае нужен сам файл.
И из хеша файла по ГОСТ 34.11-94, здесь уже готовый хеш по ГОСТ, например полученный из сервера, вместо того чтобы скачать весь файл.

**Comment by vgoma** [comment]
@nPaul один PR для проверки подписи пока висит. Если у вас идеи, создавайте PR. Глянем вместе.
