### ISSUE TITLE
Не получается подписать файл через createDetachedSignature

### ISSUE THREAD

**Issue by RomanSarvarov** [vgoma/crypto-pro#70]
Мы хотим подписывать файлы, которые лежат у нас в БД.
Для этого мы условно сделали readonly textarea, туда из БД вставили в base64 бинарный код файла.
В createDetachedSignature передаем thumbprint сертификата и хеш, в который мы положили бинарные данные файла после дешифровки из base64 через `buffer.from(binaryContent, 'base64').toString()`.

Вещи типа "hello world" подписать получается, а вот файлы посложнее типа ПДФ файла подписать не получается и приходится отказываться от работы с этой замечательной библиотекой.
В обычном примере от крипто про если мы передаем этот base64 с работающим параметром CADESCOM_BASE64_TO_BINARY всё работает, а тут почему-то не получается.

Есть идеи почему так?

**Comment by vgoma** [comment]
@RomanSarvarov ваш вопрос не содержит конкретики. Ни файла, ни реализации. Вы очевидно делаете что-то неправильно.

Загляните в [пример](https://github.com/vgoma/crypto-pro#example-script-tag). Его можно запустить на локальной машине. Работает подписание любых файлов размером до 25 МБ. Протестировано. Адаптируйте код примера под себя.
