### ISSUE TITLE
Планируются ли новые методы?

### ISSUE THREAD

**Issue by Sertata** [vgoma/crypto-pro#76]
Здравствуйте.
- Планируется ли добавление новых методов для получения сертификатов что находятся на носителях\токенах\контейнерах по аналогии с методом `getUserCertificates`?
### Например 
-  `getContainerCertificates`  или `getSmartCardUserCertificates` 

Или  отсутствие их реализации имеет  причины?

Спасибо.

**Comment by vgoma** [comment]
@Sertata добрый день.

Пакет изначально разрабатывался для Крипто ПРО v4, в котором не было такой возможности:
<img width="1515" alt="Screenshot 2023-01-08 at 12 24 03" src="https://user-images.githubusercontent.com/4262685/211188890-33f8cdf7-3a98-4fc6-9247-387873b7bf0f.png">
https://docs.cryptopro.ru/cades/reference/cadescom/cadescom_class/store?id=%D0%9C%D0%B5%D1%82%D0%BE%D0%B4%D1%8B

Плюс не было потребности работать с сертификатами, не установленными в личное хранилище.
