### ISSUE TITLE
реализация подписи в браузере с помощью Angular

### ISSUE THREAD

**Issue by zbralex** [vgoma/crypto-pro#77]
1. В консоли появляется ошибка

> crypto-pro.js:4557 GET chrome-extension://invalid/ net::ERR_FAILED

Не подскажете причину? В остальном, пакет рабочий. 
2. Есть ли метод для проверки подписи, который идет в оф. документации?
``` 
function Verify(sSignedMessage, dataInBase64) {
        return new Promise(function (resolve, reject) {
            cadesplugin.async_spawn(function* (args) {
                var oSignedData = yield cadesplugin.CreateObjectAsync("CAdESCOM.CadesSignedData");
                try {
                    // Значение свойства ContentEncoding должно быть задано
                    // до заполнения свойства Content
                    yield oSignedData.propset_ContentEncoding(CADESCOM_BASE64_TO_BINARY);
                    yield oSignedData.propset_Content(dataInBase64);
                    yield oSignedData.VerifyCades(sSignedMessage, CADESCOM_CADES_BES, true);
                } 
                catch (err) {
                    var e = cadesplugin.getLastError(err);
                    alert("Failed to verify signature. Error: " + e);
                    return args[1](e);
                }
                return args[0]();
            }, resolve, reject);
        });
    }
```

**Comment by vgoma** [comment]
> 1. В консоли появляется ошибка
> 
> > crypto-pro.js:4557 GET chrome-extension://invalid/ net::ERR_FAILED
> 
> Не подскажете причину? В остальном, пакет рабочий. 2. Есть ли метод для проверки подписи, который идет в оф. документации?
> 

Так работает cadesplugin_api.js предоставляемый Крипто ПРО. Одна из двух попыток всегда будет неудачной 😉:
<img width="1307" alt="Screenshot 2023-01-08 at 12 36 16" src="https://user-images.githubusercontent.com/4262685/211189312-d27ab96d-e5cb-4f3f-a899-4604524c9b2f.png">

> 2. Есть ли метод для проверки подписи, который идет в оф. документации?

На данный момент, нет. См:
#18
#7
