### ISSUE TITLE
Uncatched Exception in Promice ("The operation was canceled by the user. (0x000004C7)")

### ISSUE THREAD

**Issue by nobbynobbs** [vgoma/crypto-pro#8]
Привет, спасибо за вашу обертку над cadesplugin.

При использовании столкнулись со следующей проблемой: при обращении к хранилищу сертификатов или попытке подписать что-нибудь появляется диалоговое окно подтверждения доступа:

![dialog](https://user-images.githubusercontent.com/16599268/34382913-ccdfe95e-eb22-11e7-90b4-060719854d80.png)

Если в этом диалоговом окне кликнуть нет, то вылетает исключение, вот такое:

![Stacktrace screenshot](https://user-images.githubusercontent.com/16599268/34382666-8ef25236-eb21-11e7-9cba-0edd5aa0aabc.png)

Поймать это исключение не получается, соответственно нет возможности обработать ситуацию, когда пользователь не разрешил выполнение операции и как-то отреагировать на это в приложении.

Пример (утрированный) в котором эксепшн упорно вылетает наружу:
```
try {
  CryptoPro.call('getCertsList')
    .then(list =>console.log(list), e =>console.log(e))
    .catch(e => console.log(''));
} catch (e) {
  console.log(e)
}
```
при использовании async/await результат тот же самый 

Можно ли в клиентском коде обработать ситуацию когда пользователь не разрешил действия с сертификатами?

**Comment by mlshv** [comment]
У меня та же самая проблема, но, кажется, проект не поддерживается

**Comment by vgoma** [comment]
Всем привет. Последнее время не занимаюсь проектом, тк больше не сталкиваюсь с ЭП на практике. Планирую вернуться и переписать его, предоставив более современный и удобный API. Обработке ошибок уделю особое внимание. Конкретных сроков не обещаю.

Однако на момент написания возникало много проблем с перехваткой и распознаванием конкретных ошибок в силу того, что не все ошибки системного уровня пробрасывались в браузер.

Если есть конкретные идеи, не стесняйтесь создавать PR'ы.

**Comment by vgoma** [comment]
@nobbynobbs, @mlshv дополнил обработку ошибок в [**1.1.2**](https://www.npmjs.com/package/crypto-pro)
