### ISSUE TITLE
Экспорт сертификата с приватным ключом

### ISSUE THREAD

**Issue by emejibka** [vgoma/crypto-pro#84]
Здравствуйте.

Есть ли какой-нибудь способ экспортировать сертификат вместе с приватным ключом? Метод exportBase64 экспортирует только публичную часть сертификата, верно?
Мне необходимо сделать экспорт приватного ключа для последующего импорта на сервер.

**Comment by vgoma** [comment]
@emejibka добрый день. Так как экспорт закрытого ключа связан с риском его кражи злоумышленниками, данный пакет не предоставляет такой возможности.

На сколько знаю, эта задача решается средствами Крипто ПРО CSP. Попробуйте почитать раздел "Копирование с помощью КриптоПро CSP":
https://www.kontur-extern.ru/info/skopirovat-konteyner-s-sertifikatom
