### ISSUE TITLE
Для чего здесь вычисляется hash по ГОСТ Р 34.11-94 для строки: "abc" ?

### ISSUE THREAD

**Issue by domoratskii** [vgoma/crypto-pro#9]
Привет! Подскажи пожалуйста, для чего нам этот вычисленный хеш на 13стр ? Почему мы просто не передаем "abc" в `window.btoa(hash);`

https://github.com/vgoma/crypto-pro/blob/786f5fcad90a099a83477d93ea7aa2913e3453ba/example/create-sign.js#L13

**Comment by domoratskii** [comment]
Да, но есть один момент. Если проверить подпись из примера на Госуслугах, то она не пройдет. Получается, что мы получаем hashBase64 из hash а не из строки "abc".

Если будет просто `window.btoa("abc");`, то она валидна и пройдет проверку.

@nPaul

**Comment by nPaul** [comment]
Это же просто пример, автор просто заранее вычислил этот хэш из строи "abc" по ГОСТу и присвоил переменной, т.к. не суть важно

**Comment by vgoma** [comment]
@nPaul +1
